import pygame
window_size = 800
window_width = 920
window_height = 800
mousePressed = False
mousePosition = None
cardsSize = 120
game_cards=[]
all_Cards =[{"image" : pygame.image.load('PEKKA-card.png'),"position":[0,0],"type":'PEKKA',"id":0},{"image":pygame.image.load('Giant-card.png'),"position":[120,0],"type":'Giant',"id":1},{"image":pygame.image.load('Hog-card.png'),"position":[240,0],"type":'Hog',"id":2},{"image":pygame.image.load('Archer-card.png'),"position":[360,0],"type":'Archer',"id":3},{"image":pygame.image.load('Barbarian-card.png'),"position":[480,0],"type":'Barbarian',"id":4},{"image":pygame.image.load('Ballon-card.png'),"position":[600,0],"type":'Ballon',"id":5},{"image":pygame.image.load('Dragon-card.png'),"position":[720,0],"type":'Dragon',"id":6}]
menu_coordinates = [(100,200),(220,200),(340,200),(460,200),(580,200),(700,200),(820,200)]
game_coordinates = [(800,680),(800,560),(800,440),(800,320)]
draggingCard = [False,None]
tmp_mouse=None
obstacle_width = 40
path_width = 100
game_start_time = 0
low_speed = 2.5
medium_speed = 3.25
fast_speed = 4
small_size = 40
medium_size = 50
big_size = 60
AttackRange = 40
small_area_of_effect = 40
medium_area_of_effect = 50
large_area_of_effect = 60
AI_troop_list = []
AI_building_list = []
player_troop_list = []
player_building_list = []
hp_bar_offset = 10
hp_bar_width = 10
elixir_count_player = 3
last_elixir_player = 0
elixir_costs = {'Barbarian':2,'Archer':2,'Giant':5,'Hog':4,'PEKKA':7,'Dragon':4,'Ballon':5}
elixir_interval = 3000
elixir_count_AI = 0
last_elixir_AI = 0
game_started = False
game_finished = False
game_paused = False
pause_image = pygame.image.load('pause_image.png')
i = 0
menu_image = pygame.image.load('menu_image.png')
lose_image = pygame.image.load('lose_image.png')
win_image = pygame.image.load('win_image.png')